package nl.tudelft.oopp.api.models;

public class RegistrationResponse {
    String message;
    String alertType;
    Long userId;

    /**
     * A Response object sent after a login attempt by a user.
     *
     * @param message   the message that should be sent back.
     * @param alertType the type of alert that should be used.
     * @param userId    the userId that was generated by the database.
     */
    public RegistrationResponse(String message, String alertType, Long userId) {
        this.message = message;
        this.alertType = alertType;
        this.userId = userId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getAlertType() {
        return alertType;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }
}

